---
title: "Projects"
description: |
  Project descriptions 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Projects 

#### Master's Group Project (thesis equivalent)
For my Master's project, my group and I analyzed floodplain restoration opportunities in Madera County. We identified priority areas to implement multiple benefit aquifer recharge projects that utilize natural infrastructure. We mapped geospatial models in ArcGIS using publicly available scientific data to prioritize areas that could achieve floodplain mitigation benefits and ecosystem enhancement benefits. We also designed a shiny application to communicate results to stakeholders. 

To learn more about our project check out our website:  https://floodforward.wixsite.com/website

#### Communciation's Capstone 
My team and I consulted with the U.S. Fish and Wildlife Service to develop a strategic communication plan to promote the conservation of the western monarch. We developed a survey to understand California nurseries current knowledge of the western monarch decline, interest in receiving free educational materials, current milkweed plant inventory, and pesticide usage. After undergoing audience research, we developed key strategies, objectives, messages, and tactics to communicate to nurseries and nursery customers how to reverse the western monarch decline by engaging in monarch beneficial practices. We created educational signage and stickers in InDesign and Canva to be displayed at nurseries to communicate actions to reverse the monarch decline. 

